# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r docs/requirements.txt
# command to run tests
script:
  - pytest